title: Vamsi Kurama
email: vamsi.kurama@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Musings of a Computer Scientist
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vamsikurama.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vamsi_kurama
github_username:  vamsi
show_excerpts: true
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
